### ISSUE TITLE
PM Toggle doesn't work for me

### ISSUE THREAD

**Issue by EvilSlime** [HYPExMon5ter/PlayerMention-Recoded#4]
Version: Spigot 1.8.8
/pm doesn't work due PrivateMessage can you fix this?

**Comment by EvilSlime** [comment]
I'm using EssentialsX maybe that's the problem?

**Comment by HYPExMon5ter** [comment]
Do /PlayerMention then, I’ll try to think of a good alias that won’t be overridden (or you can suggest one/some)
